config/routes.rb
  # devise_scope :user do
  #   get "/users/profile", to: "users/registrations#profile", as: :user_profile
  #   patch "/users/update_password", to: "users/registrations#update_password", as: :update_user_password
  #   delete "/users/deactivate", to: "users/registrations#deactivate", as: :deactivate_user
  # end
  
    # devise_for :students


Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
 
  }

  # Profile route
  devise_scope :user do
    get "users/profile", to: "users/registrations#profile", as: :user_profile
  end
  
  # Dashboard routes for roles
  get "/admin_dashboard", to: "admin#dashboard", as: :admin_dashboard


  get '/students', to: 'students#index', as: 'index_students'

  get '/students/new', to: 'students#new', as: 'new_student' 

  post '/students', to: 'students#create'

  get '/students/:id', to: 'students#show', as: 'student'

  get '/students/:id/edit', to: 'students#edit', as: 'edit_student'

  patch '/students/:id', to: 'students#update'

  delete 'students/:id', to:'students#destroy'
  

  get '/teachers', to: 'teachers#index', as: 'index_teachers'

  get '/teachers/new', to: 'teachers#new', as: 'new_teacher' 

  post '/teachers', to: 'teachers#create'

  get '/teachers/:id', to: 'teachers#show', as: 'teacher'

  get '/teachers/:id/edit', to: 'teachers#edit', as: 'edit_teacher'

  patch '/teachers/:id', to: 'teachers#update'

  delete 'teachers/:id', to:'teachers#destroy'
  


  get '/courses', to: 'courses#index', as: 'index_courses'

  get '/courses/new', to: 'courses#new', as: 'new_course' 

  post '/courses', to: 'courses#create'

  get '/courses/:id', to: 'courses#show', as: 'course'

  get '/courses/:id/edit', to: 'courses#edit', as: 'edit_course'

  patch '/courses/:id', to: 'courses#update'

  delete 'courses/:id', to:'courses#destroy'
  

end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
#   devise :database_authenticatable, :registerable,
#          :recoverable, :rememberable, :validatable
    before_save :downcase_email

    has_many :enrollments, dependent: :destroy
    has_many :courses, through: :enrollments

    validates :name, presence: true, length: { minimum: 2}
    validates :age, presence: true,   numericality: { only_integer: true, greater_than: 2, less_than: 25}
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

    private
    def downcase_email
        self.email = email.downcase if email.present?
    end

end

app/controllers/students_controller.rb
    class StudentsController <ApplicationController
        
        # before_action :set_student, only: %i[ show edit update destroy ]
        before_action :authorize_teacher_or_admin, only: %i[new create edit update destroy]


        def index
            @student = Student.all
        end

        def show
        end

        def new
            @student = Student.new
        end

        def edit
        end

        def create
            @student = Student.new(student_params)

            if @student.save
                redirect_to index_students_path, notice: "New student added!"
            else
                puts @student.errors.full_messages 
                render :new, status: :unprocessable_entity
            end
        end

        def update

            if @student.update(student_params)
                redirect_to student_path(@student), notice: "Student updated"
            else
                puts @student.errors.full_messages  
                render :edit, status: :unprocessable_entity
            end
        end

        def destroy

            if @student.destroy
               
                redirect_to index_students_path, notice: "Student deleted"

            else
                puts @student.errors.full_messages  
                redirect_to index_students_path, alert: "Failed to delete student" 
            end
        end

        private 

        def student_params
            params.require(:student).permit(:name, :age, :email)
        end

        def set_student
            @student = Student.find(params[:id]) 
        end

        def authorize_teacher_or_admin
          unless current_user.admin? || current_user.teacher?
            redirect_to root_path, alert: "Access denied!"
          end
        end

    end     

app/views/students/_form.html.erb
<% if @student.errors.any? %>
<div style="color: red; border: 1px solid red; padding: 20px;">
  <h6><%= pluralize(@student.errors.count, "error") %> prevented saving:</h6>
  <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <h6><li><%= msg %></li></h6>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_with model: student do |form| %>
    <h4>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </h4>

    <h4> 
        <%= form.label :age %>
        <%= form.number_field :age %>
    </h4>

    <h4> 
        <%= form.label :email %>
        <%= form.email_field :email %>
    </h4>

    <h4>
        <%= form.submit 'Create Student' %>
    </h4>

<% end %>

app/views/students/edit.html.erb
<h1> Edit Student <h1>


<%= render "form", student: @student %>

<%= link_to "Back", index_students_path %>

app/views/students/index.html.erb
<h1>All Students</h1>

<div >
  <% @student.each do |std| %>
   
    <p>
        <%= link_to std.name, std %>
    </p>
  <% end %>
</div>

<%= link_to "Add Student", new_student_path %>

app/views/students/new.html.erb
<h1> Add Student <h1>

<%= render "form", student: @student %>

<%= link_to "Back", index_students_path %>

app/views/students/show.html.erb
<h4> Name: <%= @student.name %> </h4>
<h4> Age: <%= @student.age %> </h4>
<h4> Email: <%= @student.email %> </h4>

<%= link_to "Back", index_students_path %>
<%= link_to "Edit", edit_student_path(@student) %>
<p>
<%= button_to "Delete", @student, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
</p>