config/routes.rb
  # devise_scope :user do
  #   get "/users/profile", to: "users/registrations#profile", as: :user_profile
  #   patch "/users/update_password", to: "users/registrations#update_password", as: :update_user_password
  #   delete "/users/deactivate", to: "users/registrations#deactivate", as: :deactivate_user
  # end
  
    # devise_for :students


Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
 
  }

  # Profile route
  devise_scope :user do
    get "users/profile", to: "users/registrations#profile", as: :user_profile
  end
  
  # Dashboard routes for roles
  get "/admin_dashboard", to: "admin#dashboard", as: :admin_dashboard


  get '/students', to: 'students#index', as: 'index_students'

  get '/students/new', to: 'students#new', as: 'new_student' 

  post '/students', to: 'students#create'

  get '/students/:id', to: 'students#show', as: 'student'

  get '/students/:id/edit', to: 'students#edit', as: 'edit_student'

  patch '/students/:id', to: 'students#update'

  delete 'students/:id', to:'students#destroy'
  

  get '/teachers', to: 'teachers#index', as: 'index_teachers'

  get '/teachers/new', to: 'teachers#new', as: 'new_teacher' 

  post '/teachers', to: 'teachers#create'

  get '/teachers/:id', to: 'teachers#show', as: 'teacher'

  get '/teachers/:id/edit', to: 'teachers#edit', as: 'edit_teacher'

  patch '/teachers/:id', to: 'teachers#update'

  delete 'teachers/:id', to:'teachers#destroy'
  


  get '/courses', to: 'courses#index', as: 'index_courses'

  get '/courses/new', to: 'courses#new', as: 'new_course' 

  post '/courses', to: 'courses#create'

  get '/courses/:id', to: 'courses#show', as: 'course'

  get '/courses/:id/edit', to: 'courses#edit', as: 'edit_course'

  patch '/courses/:id', to: 'courses#update'

  delete 'courses/:id', to:'courses#destroy'
  

end

app/models/teacher.rb
class Teacher < ApplicationRecord

    has_one :course, dependent: :destroy
    validates :contact, presence: true, uniqueness: true, format: { with: /\A\d{10}\z/, message: "must be exactly 10 digits" }
    validates :name, presence: true, length: { minimum: 2}
end

app/controllers/teachers_controller.rb
class TeachersController <ApplicationController

    before_action :set_teacher, only: %i[ show edit update destroy ]

    def index
        @teacher = Teacher.all
    end

    def show
    end

    def new 
        @teacher = Teacher.new
    end

    def edit
    end

    def create
        @teacher = Teacher.new(teacher_params)

        if @teacher.save
            redirect_to teachers_path, notice: "New teacher added!"
        else
            puts @teacher.errors.full_messages  
            render :new, status: :unprocessable_entity
        end
    end

    def update

        if @teacher.update(teacher_params)
            redirect_to @teacher, notice: "teacher updated"
        else
            puts @teacher.errors.full_messages  
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy

        if @teacher.destroy
            redirect_to teachers_path, notice: "teacher deleted"
        else
            puts @teacher.errors.full_messages  
            redirect_to index_teachers_path, alert: "Failed to delete teacher" 
        end
    end

    private 

    def teacher_params
        params.require(:teacher).permit(:name, :contact)
    end

    def set_teacher
        @teacher = Teacher.find(params[:id]) 
    end
    
end     

app/views/teachers/_form.html.erb
<% if @teacher.errors.any? %>
<div style="color: red; border: 1px solid red; padding: 20px;">
  <h6><%= pluralize(@teacher.errors.count, "error") %> prevented saving:</h6>
  <ul>
    <% @teacher.errors.full_messages.each do |msg| %>
      <h6><li><%= msg %></li></h6>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_with model: teacher do |form| %>
    <h4>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </h4>

    <h4> 
        <%= form.label :contact %>
        <%= form.number_field :contact %>
    </h4>

    <h4>
        <%= form.submit 'Create Teacher' %>
    </h4>

<% end %>

app/views/teachers/edit.html.erb
<h1> Edit Teacher <h1>
<%= render "form", teacher: @teacher %>

<%= link_to "Back", index_teachers_path %>

app/views/teachers/index.html.erb
<h1>All Teachers</h1>

<div >
  <% @teacher.each do |teach| %>
   
    <p>
        <%= link_to teach.name, teach %>
    </p>
  <% end %>
</div>

<%= link_to "Add Teacher", new_teacher_path %>

app/views/teachers/show.html.erb
<h4> Name: <%= @teacher.name %> </h4>
<h4> Contact: <%= @teacher.contact %> </h4>


<%= link_to "Back", index_teachers_path %>
<%= link_to "Edit", edit_teacher_path(@teacher) %>
<p>
<%= button_to "Delete", @teacher, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
</p>