config/routes.rb
  # devise_scope :user do
  #   get "/users/profile", to: "users/registrations#profile", as: :user_profile
  #   patch "/users/update_password", to: "users/registrations#update_password", as: :update_user_password
  #   delete "/users/deactivate", to: "users/registrations#deactivate", as: :deactivate_user
  # end
  
    # devise_for :students


Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
 
  }

  # Profile route
  devise_scope :user do
    get "users/profile", to: "users/registrations#profile", as: :user_profile
  end
  
  # Dashboard routes for roles
  get "/admin_dashboard", to: "admin#dashboard", as: :admin_dashboard


  get '/students', to: 'students#index', as: 'index_students'

  get '/students/new', to: 'students#new', as: 'new_student' 

  post '/students', to: 'students#create'

  get '/students/:id', to: 'students#show', as: 'student'

  get '/students/:id/edit', to: 'students#edit', as: 'edit_student'

  patch '/students/:id', to: 'students#update'

  delete 'students/:id', to:'students#destroy'
  

  get '/teachers', to: 'teachers#index', as: 'index_teachers'

  get '/teachers/new', to: 'teachers#new', as: 'new_teacher' 

  post '/teachers', to: 'teachers#create'

  get '/teachers/:id', to: 'teachers#show', as: 'teacher'

  get '/teachers/:id/edit', to: 'teachers#edit', as: 'edit_teacher'

  patch '/teachers/:id', to: 'teachers#update'

  delete 'teachers/:id', to:'teachers#destroy'
  


  get '/courses', to: 'courses#index', as: 'index_courses'

  get '/courses/new', to: 'courses#new', as: 'new_course' 

  post '/courses', to: 'courses#create'

  get '/courses/:id', to: 'courses#show', as: 'course'

  get '/courses/:id/edit', to: 'courses#edit', as: 'edit_course'

  patch '/courses/:id', to: 'courses#update'

  delete 'courses/:id', to:'courses#destroy'
  

end

app/controllers/courses_controller.rb
class CoursesController <ApplicationController

    before_action :set_course, only: %i[ show edit update destroy ]

    def index
        @course = Course.all
    end

    def show
    end

    def new
        @course = Course.new
    end

    def edit
    end

    def create  
        @course = Course.new(course_params)

        if @course.save
            redirect_to index_courses_path, notice: "New course added!"
        else
            puts @course.errors.full_messages  
            render :new, status: :unprocessable_entity
        end
    end

    def update

        if @course.update(course_params)
            redirect_to course_path(@course), notice: "course updated"
        else
            puts @course.errors.full_messages  
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy

        if @course.destroy
            redirect_to index_courses_path, notice: "course deleted"
        
        else
            puts @course.errors.full_messages  
            redirect_to index_courses_path, alert: "Failed to delete courses" 
        end
    end

    private 

    def course_params
        params.require(:course).permit(:name, :description)
    end


    def set_course
        @course = Course.find(params[:id]) 
    end

    
end     

app/views/courses/_form.html.erb
<% if @course.errors.any? %>
<div style="color: red; border: 1px solid red; padding: 20px;">
  <h6><%= pluralize(@course.errors.count, "error") %> prevented saving:</h6>
  <ul>
    <% @course.errors.full_messages.each do |msg| %>
      <h6><li><%= msg %></li></h6>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_with model: course do |form| %>
    <h4>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </h4>

    <h4> 
        <%= form.label :description %>
        <%= form.text_field :description %>
    </h4>

    <h4>
        <%= form.submit 'Create Course' %>
    </h4>

<% end %>

app/views/courses/edit.html.erb
<h1> Edit Course <h1>
<%= render "form", course: @course %>

<%= link_to "Back", index_courses_path %>

app/views/courses/index.html.erb
<h1>All Course</h1>

<div >
  <% @course.each do |course_| %>
   
    <p>
        <%= link_to course_.name, course_ %>
    </p>
  <% end %>
</div>

<%= link_to "Add Course", new_course_path %>

app/views/courses/show.html.erb
<h4> Name: <%= @course.name %> </h4>
<h4> Description: <%= @course.description %> </h4>


<%= link_to "Back", index_courses_path %>
<%= link_to "Edit", edit_course_path(@course) %>
<p>
<%= button_to "Delete", @course, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
</p>