config/routes.rb
  # devise_scope :user do
  #   get "/users/profile", to: "users/registrations#profile", as: :user_profile
  #   patch "/users/update_password", to: "users/registrations#update_password", as: :update_user_password
  #   delete "/users/deactivate", to: "users/registrations#deactivate", as: :deactivate_user
  # end
  
    # devise_for :students


Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
 
  }

  # Profile route
  devise_scope :user do
    get "users/profile", to: "users/registrations#profile", as: :user_profile
  end
  
  # Dashboard routes for roles
  get "/admin_dashboard", to: "admin#dashboard", as: :admin_dashboard


  get '/students', to: 'students#index', as: 'index_students'

  get '/students/new', to: 'students#new', as: 'new_student' 

  post '/students', to: 'students#create'

  get '/students/:id', to: 'students#show', as: 'student'

  get '/students/:id/edit', to: 'students#edit', as: 'edit_student'

  patch '/students/:id', to: 'students#update'

  delete 'students/:id', to:'students#destroy'
  

  get '/teachers', to: 'teachers#index', as: 'index_teachers'

  get '/teachers/new', to: 'teachers#new', as: 'new_teacher' 

  post '/teachers', to: 'teachers#create'

  get '/teachers/:id', to: 'teachers#show', as: 'teacher'

  get '/teachers/:id/edit', to: 'teachers#edit', as: 'edit_teacher'

  patch '/teachers/:id', to: 'teachers#update'

  delete 'teachers/:id', to:'teachers#destroy'
  


  get '/courses', to: 'courses#index', as: 'index_courses'

  get '/courses/new', to: 'courses#new', as: 'new_course' 

  post '/courses', to: 'courses#create'

  get '/courses/:id', to: 'courses#show', as: 'course'

  get '/courses/:id/edit', to: 'courses#edit', as: 'edit_course'

  patch '/courses/:id', to: 'courses#update'

  delete 'courses/:id', to:'courses#destroy'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "School Management System" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
      <p>Welcome, <%= current_user.email %>!</p>

        <% if current_user.admin? %>
          <%= link_to "Admin Dashboard", admin_dashboard_path %>
        <% end %>

        <% if current_user.teacher? %>
          <%= link_to "Teacher Dashboard", index_teachers_path %>
        <% end %>

        <% if current_user.student? %>
          <%= link_to "Student Dashboard", index_students_path %>
        <% end %>
        <%= link_to "Profile", user_profile_path %>
      
        <%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete, confirm: "Are you sure you want to log out?" } %>

    <% end %>


    <%= yield %>
  </body>
</html>